apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: sock-shop
data:
  alertmanager.yaml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/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
      
    route:
      group_by: ['alertname', 'namespace', 'pod']
      receiver: "slack-notifications"

    receivers:
    - name: "slack-notifications"
      slack_configs:
      - channel: "#general"
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
