apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: sock-shop
  labels:
    role: prometheus-rulefiles
data:
  alert-rules.yaml: |-
    groups:
    - name: example
      rules:
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latency
          description: "Request latency is over 0.5s for 10 minutes."